basePath: /
host: ws-fatwa.herokuapp.com
info:
  contact:
    email: 1214038@std.ulbi.ac.id
    name: API Support
    url: https://github.com/Fatwaff
  description: This is a sample server
  title: Swagger Example API
  version: "1.0"
paths: {}
schemes:
- http
- https
swagger: "2.0"
